### PR TITLE
fix for opencv

### PR DESCRIPTION
**Pull request by PeterMitrano**
ros-(kinetic|melodic|noetic)-vision-opencv all use opencv2, so this should be safe.

### CODE REVIEW

**Comment by PeterMitrano** [comment]
I'd like to try testing this on kinetic/melodic -- is there a quick way to do that with docker?

**Comment by PeterMitrano** [comment]
optionally, we could try copying over the .travis from arc_utilities?

**Comment by bsaund** [comment]
you could set up another travis if you felt like putting in the effort.

`loki` already has `sdf` tools and kinetic, so I'll test there

**Comment by bsaund** [comment]
It builds under kinetic.
The "tests" run. LGTM


```
voxel_grid_test
estimate_distance_test
compute_convex_segments_test
```

**Review by bsaund — APPROVED** [review]

**Pull request merged**
