### PR TITLE
Updated projection function to use a margin to avoid numerical problems.

### PR DESCRIPTION
**Pull request by dmcconachie**

### CODE REVIEW

**Comment by calderpg** [comment]
Passing location (Eigen::Vector4d) by value is unsafe and breaks alignment requirements. Eigen docs explain that all Eigen types must be passed by const or mutable reference. In this case it must be passed as a const reference and then a mutable copy made. This is because the alignment constraints for RAII'd and new'd objects do not apply to pass-by-value objects.

**Comment by dmcconachie** [comment]
Aah, that's why the original code passed by reference then made an explicit copy. I'll make that change and add a comment to the code to explain why it's being done this way.

**Comment by calderpg** [comment]
Is there a reason the multiplier is 1/10 rather than 1/8 or something similar that can be exactly represented with a double? If possible, operations on unit or exactly-represented grid sizes should reduce the amount of numerical error.

**Comment by dmcconachie** [comment]
No specific reason for that default, I'm fine with changing the default to 1/8.

**Comment by calderpg** [comment]
grad_eigen should be an Eigen::Vector4d(x, y, z, 0.0) to enable SIMD math instructions

**Comment by calderpg** [comment]
Other than that, it looks OK. Is there a reason to prefer division by constant over multiplication by constant?

**Comment by dmcconachie** [comment]
In the case of the  `/ 4.0` not really. In the case of the default stepsize multiplier, `0.125` is (to me) a less intuitive number than `1.0 / 8.0`, and the compiler should handle the conversion for no runtime cost.

**Pull request merged**
