### PR TITLE
Move implementations to cpp file

### PR DESCRIPTION
**Pull request by dmcconachie**

### CODE REVIEW

**Comment by calderpg** [comment]
If this is going to be merged, the same changes should be done to all sdf_tools classes to be consistent. The compile-time speedup of moving one with be minimal if the others are not also moved.

**Comment by calderpg** [comment]
This also means that sdf_tools must be linked to, rather than included. This does affect some specific uses of the codebase.

**Comment by calderpg** [comment]
Also, the serialization/deserialization should be switched to use arc_helpers directly.

**Comment by dmcconachie** [comment]
Which other parts of the codebase are you referring to? Wouldn't those be using catkin_package to find this, and thus it'll happen automatically?

**Comment by dmcconachie** [comment]
The serialization/deserialization shoiuld be a different set of changes.

**Comment by calderpg** [comment]
The de/serialization changes are 1 line a piece in two places. Given the scope of changes here, they should be made. It's just sloppy not to. Similarly, if the issue is long compile times for sdf_tools, then the changes need to made to collision_map and potentially tagged_object_collision_map as well, or there will be no meaningful improvement.

**Comment by dmcconachie** [comment]
Any other repos that should be tested against this change?

**Comment by calderpg** [comment]
uncertainty_planning_core and fast_kinematic_simulator should be tested against it. I would suggest a quick performance test of one of the planners to see if these changes have any performance impacts.

**Comment by dmcconachie** [comment]
Ruikun, can I get you to try these changes at some point (not urgent) and let me know if there are any problems?

**Comment by calderpg** [comment]
For comparison purposes, we should pick a common set of parameters to test the planner with. We can compare the performance with the new code that Ruikun tests with the results on my end.

Let's go with:
```
rosrun uncertainty_planning_examples se3_contact_planning_node
```
using the default parameters.

If you delete the current log file (`/tmp/se3_planner_log.txt`) and run it a few times (preferably at least 10) then I can look at the log file an see if the performance has changed.

**Comment by dmcconachie** [comment]
[sdf_as_libraray.tar.gz](https://github.com/UM-ARM-Lab/sdf_tools/files/1264595/sdf_as_libraray.tar.gz)
[sdf_as_mostly_header.tar.gz](https://github.com/UM-ARM-Lab/sdf_tools/files/1264596/sdf_as_mostly_header.tar.gz)

**Comment by dmcconachie** [comment]
Tests on arcflame (Dropbox was still enabled while tests ran, so some noise in the data).
[se3_planner_log_sdf_as_library.txt](https://github.com/UM-ARM-Lab/sdf_tools/files/1265018/se3_planner_log_sdf_as_library.txt)
[se3_planner_log_sdf_mostly_header.txt](https://github.com/UM-ARM-Lab/sdf_tools/files/1265019/se3_planner_log_sdf_mostly_header.txt)

**Comment by dmcconachie** [comment]
Any update on this?

**Comment by calderpg** [comment]
In terms of performance impact, moving implementations to the library results in equivalent performance to the header version. At this point, the Xeon Phi simulation backend needs major rework anyways, so nothing is lost by moving the relevant parts out of the headers.

**Pull request merged**
