### PR TITLE
[Feature] Visualization tweaks

### PR DESCRIPTION
**Pull request by dmcconachie**
In particular, adds options for visualizing each tagged object in its own namespace, to allow for easy toggling in RViz.

### CODE REVIEW

**Comment by bsaund** [comment]
@PeterMitrano @dmcconachie 
We should either merge this or drop it.
I don't use sdf_tools so I don't care, but it's a little old

**Comment by dmcconachie** [comment]
This is currently used by `deform_simulator`: https://github.com/UM-ARM-Lab/deform_control/blob/master/deform_simulator/src/custom_scene/custom_scene.cpp#L3509; so it was still entirely the last time I was using any of this code.

**Comment by PeterMitrano** [comment]
I say we yolo merge it

**Comment by PeterMitrano** [comment]
it compiles so I'm merging

**Pull request merged**
